name: Fly.io Production Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ./src
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
